// 繁體中文（台灣）介面文字。鍵值與 strings.js 的英文表相同。

export const zhTW = {
  title: '跟著負載走',
  skip: '跳到主要內容',
  tagline: '讓台灣這座孤島電網維持 60 Hz 一整天。',
  loading: '載入中…',
  'version.title': '版本 {version}，發布日期 {date}。開啟更新紀錄。',
  'error.title': '無法載入遊戲資料',
  'error.hint': '如果你是直接從資料夾開啟 index.html，請改為執行 `npm start`，再開啟 http://localhost:8000。',

  'steps.label': '步驟',
  'step.1': '認識遊戲',
  'step.2': '設定電網',
  'step.3': '開始調度',

  'intro.heading': '你是電網調度員',
  'intro.p1': '台灣電網是一座孤島，沒有鄰國可以借電。每一刻，發電廠的出力都必須剛好等於全台的用電量。',
  'intro.p2': '這個平衡會反映在電網頻率上。發電不足，頻率就會低於 60 Hz；發電過多，頻率就會上升。偏離太多，保護電驛會自動切離用戶，甚至整個電網崩潰停電。',
  'intro.goalHeading': '你的目標',
  'intro.goal1': '一整天都讓頻率維持在綠色區間（59.8–60.2 Hz）。',
  'intro.goal2': '注意負載預測，提早幾個小時啟動起動慢的電廠。',
  'intro.goal3': '用反應快的機組、儲能和需量反應，跟上負載的起伏。',
  'intro.lessonHeading': '核心觀念',
  'intro.lesson': '電網穩定靠的是彈性，也就是跟著負載調整的能力，而不是讓大型電廠滿載運轉。',
  'intro.next': '下一步：設定你的電網',

  'setup.heading': '設定你的電網',
  'setup.fleet': '電源組合',
  'setup.day': '選擇哪一天？',
  'setup.difficulty': '難度與選項',
  'setup.accidents': '意外事件',
  'accidents.none': '無',
  'accidents.none.hint': '平靜的一天。',
  'accidents.scheduled': '固定發生',
  'accidents.scheduled.hint': '在固定時間一定會發生的事件：颱風、歷史跳機事件。',
  'accidents.random': '隨機發生',
  'accidents.random.hint': '隨機時間的突發狀況：機組跳機、雲層、風力驟降、負載突增。',
  'accidents.both': '兩者都有',
  'accidents.both.hint': '固定事件加上隨機突發狀況。',
  'setup.autoStorage': '自動：儲能與需量反應',
  'setup.autoStorageHint': '電池和抽蓄水力會自動充放電；供電不足時需量反應自動介入。也可以在卡片上個別切換。',
  'setup.autoFollow': '自動：核能、燃煤與燃氣機組跟隨負載',
  'setup.autoFollowHint': '運轉中的核能、燃煤與燃氣複循環機組會在升降載速度限制內自動調整出力。要讓幾部機組運轉或熱機備轉，仍由你決定。',
  'setup.autoRenewables': '自動：水力、太陽光電與風力',
  'setup.autoRenewablesHint': '水力在供電不足時補上並替之後保留水量；太陽光電與風力全力發電，只有在電力多到無處可用時才降載。',
  'setup.autoBackup': '自動：燃氣尖峰與燃油機組備援',
  'setup.autoBackupHint': '尖峰與燃油機組在熱機備轉待命，供電不足時自動起動，便宜的先上。',
  'setup.assist': '輔助：自動調速器反應',
  'setup.assistHint': '頻率偏移時，運轉中的電廠會自動微調出力，幫你補救小失誤。',
  'setup.summary': '今天的電網',
  'setup.peakToday': '今日尖峰負載',
  'setup.firm': '可靠容量',
  'setup.flexible': '儲能與需量反應',
  'setup.renewable': '太陽光電與風力裝置容量',
  'setup.margin': '可靠容量＋儲能高於尖峰',
  'setup.marginLow': '可靠容量加儲能不足以應付今日尖峰，可能需要卸載。',
  'setup.data': '關於資料',
  'setup.back': '上一步',
  'setup.start': '開始這一天',
  'setup.customHeading': '自訂電源組合（GW）',
  'setup.customBase': '起始組合',
  'setup.customPeak': '年度尖峰負載',
  'setup.meterFirm': '可靠容量',
  'setup.meterFlex': '儲能＋需量反應',
  'setup.meterPeak': '尖峰',
  'setup.fleetFacts': '年度尖峰 {peak} · 光電＋風力 {re}',
  'fleet.custom.name': '自訂組合',
  'fleet.custom.description': '自己決定每種電源的裝置容量，看看需要什麼才撐得住。',
  'data.partial': '真實總量',
  'data.placeholder': '推估情境',
  'data.custom': '你的數字',
  'data.daysNote': '每日負載曲線為示意資料，並依真實年度尖峰縮放。',

  'difficulty.easy': '簡單',
  'difficulty.easy.hint': '開啟輔助，沒有意外事件。',
  'difficulty.normal': '普通',
  'difficulty.normal.hint': '沒有輔助，會發生情境事件。',
  'difficulty.hard': '困難',
  'difficulty.hard.hint': '沒有輔助，預測有誤差，還有突發跳機。',

  'play.clockLabel': '時間',
  'speed.label': '速度',
  'speed.pause': '暫停',
  'speed.play': '播放',
  'speed.x': '{n}×',
  'play.help': '顯示教學',
  'play.restart': '重新開始這一天',
  'play.quit': '變更設定',
  'freq.label': '電網頻率',
  'band.normal': '正常',
  'band.warning': '警戒',
  'band.critical': '危急',
  'band.blackout': '停電',
  'band.shedding': '卸載中',

  'chart.title': '負載與供電',
  'chart.label': '一天中各類電源供電與負載的圖表。可用左右方向鍵讀取數值。',
  'chart.demand': '負載',
  'chart.forecast': '負載預測',
  'chart.netForecast': '淨負載預測（扣除光電與風力）',
  'chart.charging': '負載＋儲能充電',
  'chart.now': '現在',
  'chart.mini': '負載與供電（點一下看完整圖表）',
  'chart.freqTitle': '頻率',
  'chart.hz': '{v} Hz',

  'group.nuclear': '核能',
  'group.coal': '燃煤',
  'group.gas': '燃氣',
  'group.hydro': '水力',
  'group.wind': '風力',
  'group.solar': '太陽光電',
  'group.storage': '儲能',
  'group.other': '燃油、需量反應、自動反應',

  'stat.demand': '負載',
  'stat.demandHint': '含 {mw} MW 儲能充電',
  'stat.supply': '供電',
  'stat.imbalance': '供需差',
  'stat.inertia': '慣量',
  'stat.inertiaHint': '{kinetic} GW·s 旋轉動能',
  'stat.reserve': '備轉容量',
  'stat.reserveHint': '可升 {up} · 可降 {down}',
  'stat.auto': '自動反應',
  'meter.co2': '目前碳排強度',
  'meter.co2Value': '{v} g/kWh',
  'meter.co2Foot': '今日平均 {avg} g/kWh · 累計 CO₂ {kt} kt',
  'meter.cost': '目前燃料成本',
  'meter.costValue': 'NT$ {v}/kWh',
  'meter.costFoot': '每小時 NT$ {rate} M · 今日累計 NT$ {total} M，其中燃氣與燃油 NT$ {gasOil} M',
  'fuel.nuclear': '核能',
  'fuel.coal': '燃煤',
  'fuel.gas': '燃氣',
  'fuel.oil': '燃油',
  'fuel.other': '水力、需量反應',
  'fuel.renewable': '太陽光電、風力',
  'fuel.storage': '儲能',
  'fuel.costPerKWh': 'NT$ {v}/度',
  'fuel.free': 'NT$ 0 · 免燃料',
  'meter.bySource': '各電源每度燃料成本',
  'meter.share': '目前占比',
  'stat.curtailed': '目前棄電',
  'stat.shed': '被切離的用戶',
  'imbalance.surplus': '供過於求',
  'imbalance.shortfall': '供不應求',
  'imbalance.balanced': '平衡',
  'events.heading': '調度中心紀錄',
  'events.empty': '目前一切平靜。',
  'events.more': '顯示全部 {n} 則訊息',
  'events.less': '收合',

  'unit.status.offline': '停機',
  'unit.status.warming': '暖機中',
  'unit.status.standby': '熱機備轉',
  'unit.status.starting': '起動中',
  'unit.status.online': '運轉中',
  'unit.status.stopping': '停機中',
  'unit.fleet': '{count} 部機組 × {size} MW',
  'unit.fleetStatus': '運轉 {online}/{count}',
  'unit.fleetTarget': '目標 {setpoint} · 併聯容量 {online} MW',
  'unit.pending': '{n} 部起動中，下一部 {time}後併聯',
  'unit.warmingUp': '{n} 部暖機中',
  'unit.stoppingN': '{n} 部停機中',
  'unit.offlineCount': '{n} 部停機',
  'unit.startTimes': '起動：冷機 {cold}，熱機 {warm}',
  'unit.onlinePlus': '多一部 {name} 機組併聯',
  'unit.onlineMinus': '少一部 {name} 機組併聯',
  'unit.standbyPlus': '多暖機一部 {name} 機組待命',
  'unit.standbyMinus': '讓一部待命的 {name} 機組冷機',
  'unit.auto': '自動',
  'unit.autoOn': '自動控制中',
  'unit.output': '{output} MW',
  'unit.setpoint': '目標 {setpoint} · 上限 {max}',
  'unit.startsIn': '{time}後併聯',
  'unit.startupTakes': '起動需要 {time}',
  'unit.lockedOut': '今天無法再起動',
  'unit.stopping': '正在降載停機',
  'unit.soc': '電量 {pct}% · 剩 {energy}',
  'unit.water': '今日剩餘水量 {pct}%',
  'unit.dsm': '剩餘可抑低時間 {time}',
  'unit.variable': '可發 {available} MW · 棄電 {curtailed} MW',
  'unit.thermal': '升降載 ±{ramp} MW/分 · 最低 {min} MW',
  'unit.decrease': '降低 {name}',
  'unit.increase': '提高 {name}',
  'unit.start': '起動',
  'unit.stop': '停機',
  'unit.cancel': '取消',
  'units.heading': '電廠',
  'units.hint': '空白鍵暫停 · 數字鍵選機組 · ↑/↓ 調整',

  'unitType.nuclear': '核能',
  'unitType.coal': '燃煤',
  'unitType.gasCcgt': '燃氣（複循環）',
  'unitType.gasOcgt': '燃氣（尖峰機組）',
  'unitType.oil': '燃油',
  'unitType.hydro': '水力',
  'unitType.pumpedHydro': '抽蓄水力',
  'unitType.battery': '儲能電池',
  'unitType.dsm': '需量反應',
  'unitType.solar': '太陽光電',
  'unitType.wind': '風力',

  'time.hm': '{h} 小時 {m} 分',
  'time.h': '{h} 小時',
  'time.m': '{m} 分鐘',

  'event.trip': '{tech} 有 {n} 部機組跳機！瞬間失去 {mw} MW。',
  'event.windLull': '風突然減弱，風力出力下降。',
  'event.demandSurge': '負載突然高於預測。',
  'event.clouds': '雲層飄過西部沿海，太陽光電出力下降。',
  'event.windCutout': '颱風風速超過風機上限，風場自動停機保護。',
  'event.warning.windCutout': '颱風警報：風場約在 {time} 開始停機，請現在就準備替代電源。',
  'event.warning.clouds': '天氣預報：約 {time} 會有雲層。',
  'event.shed': '低頻電驛切離用戶（第 {stage} 段，負載的 {pct}%）。',
  'event.restore': '頻率恢復，用戶已復電（尚餘第 {stage} 段）。',
  'note.datan2017': '2017 年 8 月 15 日曾發生類似事件：供氣異常導致大潭電廠機組跳機，數百萬戶輪流停電。',
  'note.hsinta2022': '2022 年 3 月 3 日曾發生類似事件：興達電廠附近的變電所故障，引發大範圍停電。',

  'end.finished': '完成這一天',
  'end.blackout': '全面停電',
  'end.blackoutSub': '頻率在 {time} 超出安全範圍，電網崩潰。',
  'end.finishedSub': '你讓台灣電網運轉了 24 小時。',
  'end.score': '{points} / {max} 分',
  'kpi.reliability': '供電可靠度：頻率正常時間',
  'kpi.reliabilityHint': '沒有卸載',
  'kpi.reliabilityShed': '卸載 {n} 段',
  'kpi.cost': '成本：發電成本',
  'kpi.costHint': '總計 NT$ {total} M',
  'kpi.carbon': '碳排：CO₂ 排放強度',
  'kpi.carbonHint': '總計 CO₂ {kt} kt',
  'kpi.score': '{score}/100 · 權重 {weight}%',
  'end.stars': '3 顆星中得到 {n} 顆',
  'end.shed': '卸載段數',
  'end.unserved': '未供應電量',
  'end.gasOil': '燃氣與燃油花費',
  'end.re': '光電與風力占比',
  'end.curtailed': '再生能源棄電',
  'end.lesson': '學到什麼',
  'end.again': '再玩一次',
  'end.setup': '變更設定',

  'lesson.blackoutHigh': '發電太多了。負載下降或風變大時，總得有機組降載、儲能充電或棄電，而大型基載電廠很難快速降載。',
  'lesson.blackoutLowInertia': '運轉中的旋轉機組太少，電網慣量很低，頻率掉得太快來不及救。低慣量電網需要事先準備好電池這類快速反應的資源。',
  'lesson.blackoutEvening': '晚間尖峰讓你措手不及。太陽下山時負載仍然很高，要在日落前幾小時啟動慢機組，並備好快速備轉。',
  'lesson.blackoutLow': '發電跟不上負載。注意預測，並保留備轉容量（運轉中機組的升載空間）以應付突發狀況。',
  'lesson.shedding': '自動卸載救了電網 {stages} 次，但用戶停電了。陡峭升載或高風險時段之前，要準備更多備轉容量。',
  'lesson.tooMuch': '你常常發電過多。有彈性的電網在負載下降時會降載、儲能或棄電，而缺乏彈性的基載讓這件事很難做到。',
  'lesson.eveningRamp': '晚間升載是最難的時刻：光電消退，負載卻仍然很高。日落前就要讓燃氣機組併聯。',
  'lesson.morningRamp': '早晨升載是最難的時刻。全島醒來時負載快速攀升，要提前增加出力。',
  'lesson.tooLittle': '你常常發電不足。跟著預測線走並提早起動機組，慢機組需要好幾個小時的準備。',
  'lesson.curtailment': '你保住了供電，卻浪費了 {pct}% 的光電與風電。中午讓儲能充電、抽蓄抽水，就能把電留到晚上用。',
  'lesson.expensive': '供電穩定，但很貴：燃氣與燃油占了燃料費的 {pct}%。提早讓便宜的機組併聯，把尖峰機組和燃油留給真正的緊急狀況。',
  'lesson.carbon': '供電穩定，但碳排高：每度電 {g} 克 CO₂。多用太陽光電、風力與儲能，少用燃煤與燃油，就能減少排放。',
  'lesson.wellDone': '平衡得很好！你跟上了負載：穩定電廠顧基載，彈性電源應付起伏。',

  'tutorial.next': '下一步',
  'tutorial.done': '開始吧',
  'tutorial.skip': '跳過教學',
  'tutorial.step': '提示 {n}／{total}',
  'tutorial.1': '這是電網頻率，要讓它留在綠色區間。負載高於供電時頻率下降，供電高於負載時頻率上升。',
  'tutorial.2': '圖表以堆疊方式顯示各類電源的供電，並與負載線比較。前方的虛線是預測，請依此規劃。',
  'tutorial.3': '每張卡片代表一種電源。− 和 + 調整所有運轉中機組的出力；「運轉中」和「熱機備轉」的數字用來增減機組。慢機組冷機起動要好幾個小時，從熱機備轉快得多。',
  'tutorial.4': '慣量與備轉容量代表電網此刻有多強韌。旋轉機組越少，頻率變動越快。',
  'tutorial.5': '在這裡控制時間，隨時可以暫停（空白鍵）思考。調度員，祝你好運！',

  // Names and descriptions from data files.
  'scenario.taiwan-2016.name': '台灣 2016',
  'scenario.taiwan-2016.description': '燃煤與核能撐起負載，光電和風力還很少。大型穩定電廠，旋轉慣量充足。',
  'scenario.taiwan-2025.name': '台灣 2025',
  'scenario.taiwan-2025.description': '核能已退場，燃氣成為主力。中午光電很多，太陽下山後其他機組必須快速升載迎接晚間尖峰。',
  'scenario.taiwan-2050.name': '台灣 2050',
  'scenario.taiwan-2050.description': '淨零路徑：大量光電與風電（陸域與離岸）、大型電池與彈性負載，旋轉機組很少，所以頻率變化很快。',
  'scenario.taiwan-2016.dataNotes': '年度尖峰負載與各類電源裝置容量為 2016 年官方數字。機組分組、儲能容量、需量反應規模與所有機組參數為示意值。未納入生質能與廢棄物發電（0.7 GW）。',
  'scenario.taiwan-2025.dataNotes': '年度尖峰負載與各類電源裝置容量為 2025 年官方數字，電池規模採用 2025 年電網儲能目標。機組分組、儲能容量、需量反應規模與所有機組參數為示意值。未納入生質能、廢棄物與地熱發電（0.8 GW）。',
  'scenario.taiwan-2050.dataNotes': '這是假設情境，並非官方規劃。尖峰負載是把官方每年 1.7% 的成長展望延伸到 2050 年；再生能源占比依 2050 淨零路徑 60–70% 的目標；各電源容量分配與機組參數為示意值。燃氣機組代表低碳的可靠電源（可燒氫或搭配碳捕捉）。',
  'day.summerWeekday.name': '夏季平日',
  'day.summerWeekday.description': '七月一個炎熱的星期二。冷氣讓負載在午後衝上全年尖峰，光電一直強到日落。',
  'day.summerWeekend.name': '夏季週末',
  'day.summerWeekend.description': '七月的星期日。辦公室和工廠較安靜，大家回家後負載在晚上達到尖峰。',
  'day.winterWeekday.name': '冬季平日',
  'day.winterWeekday.description': '一月的星期三。負載較低，白天短、日照弱，東北季風帶來強風。',
  'day.winterWeekend.name': '冬季週末',
  'day.winterWeekend.description': '一月的星期六。負載低，風力充足、中午還有陽光：小心發電過多。',
  'day.lunarNewYear.name': '農曆春節',
  'day.lunarNewYear.description': '工廠放年假，負載降到全年最低，但陽光和風照樣發電。',
  'day.typhoon.name': '颱風天',
  'day.typhoon.description': '八月的颱風假。辦公室停班，雲層遮住陽光，午後風勢強到風機必須停機保護。',
};
