// Imports real weather for each day type from the Taiwan energy model
// (https://github.com/BartonChenTW/taiwan-energy-model) and writes
// data/weather-days.json, which tools/make-days.js turns into the solar and
// wind profiles of data/days.json.
//
// The model's full-year runs (docs/data/cases/*.json) hold 4-hour average
// capacity factors for solar, onshore and offshore wind, from reanalysis
// weather for 2013 and 2018. Timestamps are UTC; Taiwan is UTC+8, so a local
// day is the six windows starting at 16:00 UTC the day before.
//
// Run: node tools/import-weather.js <path to a taiwan-energy-model checkout>
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const CASES = {
  2013: 'tw_test2_highs_2013_fullyear_4h_6b_ls__elec_s_6_ec_lv1.0_Co2L-4H.json',
  2018: 'tw_weather2018_highs_fullyear_4h_6b_ls__elec_s_6_ec_lv1.0_Co2L-4H.json',
};

// One real date per day type, and why it was chosen.
const DAYS = {
  summerWeekday: { date: '2018-07-24', why: 'the July 2018 Tuesday with the median wind output, leaving out the two typhoon days (3 and 10 July)' },
  summerWeekend: { date: '2018-07-01', why: 'the July 2018 Sunday with the median solar output' },
  winterWeekday: { date: '2018-01-24', why: 'the January 2018 Wednesday with the median wind output' },
  winterWeekend: { date: '2018-01-13', why: 'the January 2018 Saturday with the most sun and wind together' },
  lunarNewYear: { date: '2018-02-16', why: 'Lunar New Year\'s Day 2018' },
  typhoon: { date: '2013-08-21', why: 'Typhoon Trami, a typhoon day off in northern Taiwan' },
  lngBlockade: { date: '2013-07-05', why: 'day 5 of the model\'s summer blockade window (it starts 1 July 2013)' },
};

const round = (x) => Math.round(x * 1000) / 1000;

const root = process.argv[2];
if (!root) {
  console.error('usage: node tools/import-weather.js <taiwan-energy-model checkout>');
  process.exit(1);
}

const years = {};
for (const [year, file] of Object.entries(CASES)) {
  const { inputs } = JSON.parse(readFileSync(join(root, 'docs/data/cases', file), 'utf8'));
  years[year] = { file, time: inputs.time.map((s) => Date.parse(`${s.replace(' ', 'T')}Z`)), availability: inputs.availability };
}

const days = {};
for (const [id, { date, why }] of Object.entries(DAYS)) {
  const y = years[date.slice(0, 4)];
  const start = Date.parse(`${date}T00:00:00+08:00`);
  const idx = y.time.map((t, i) => [t, i]).filter(([t]) => t >= start && t < start + 86400000).map(([, i]) => i);
  if (idx.length !== 6) throw new Error(`${id}: expected six 4-hour windows on ${date}, found ${idx.length}`);
  const pick = (carrier) => idx.map((i) => round(y.availability[carrier][i]));
  days[id] = {
    date,
    why,
    source: `taiwan-energy-model docs/data/cases/${y.file}`,
    solar: pick('solar'),
    onwind: pick('onwind'),
    offwind: pick('offwind-ac'),
  };
}

const out = {
  _comment: 'Generated by tools/import-weather.js from the Taiwan energy model. solar, onwind, offwind: 4-hour average capacity factors for the local day (00-04, 04-08, ..., 20-24 Taiwan time).',
  days,
};
const json = JSON.stringify(out, null, 2).replace(/\[\s*([-\d.,\s]+?)\s*\]/g, (_, body) => `[${body.split(/\s*,\s*/).join(', ')}]`);
writeFileSync(new URL('../data/weather-days.json', import.meta.url), json + '\n');
console.log(`Wrote ${Object.keys(days).length} days to data/weather-days.json`);
