// Generates data/days.json: hourly demand shapes and renewable capacity
// factors for each day type. Run: `node tools/make-days.js`
//
// PLACEHOLDER DATA. The demand shapes are hand-drawn to resemble typical
// Taiwanese daily load curves (night trough, lunchtime dip, afternoon peak in
// summer, evening peak in winter) and are scaled in-game to the real annual
// peak of each scenario. Replace them with measured Taipower curves when
// available (see README "Data sources").
import { writeFileSync } from 'node:fs';

const round = (x) => Math.round(x * 1000) / 1000;

/** Solar capacity factor at hour h for a clear-ish day: a sine hump between sunrise and sunset. */
function solarCurve(h, sunrise, sunset, peak) {
  if (h <= sunrise || h >= sunset) return 0;
  return peak * Math.sin((Math.PI * (h - sunrise)) / (sunset - sunrise)) ** 1.3;
}

const hours = [...Array(24).keys()];
const solar = (sunrise, sunset, peak) => hours.map((h) => round(solarCurve(h, sunrise, sunset, peak)));
const wind = (base, amp, peakHour) =>
  hours.map((h) => round(Math.max(0, base + amp * Math.cos((2 * Math.PI * (h - peakHour)) / 24))));

const days = [
  {
    id: 'summerWeekday',
    name: 'Summer weekday',
    description: 'A hot Tuesday in July. Air-conditioning drives demand to the year\'s peak in the early afternoon; solar is strong until sunset.',
    month: 7,
    weekday: 2,
    peakRatio: 1.0,
    load: [0.8, 0.77, 0.75, 0.73, 0.72, 0.72, 0.74, 0.8, 0.88, 0.94, 0.97, 0.98, 0.93, 0.97, 1.0, 1.0, 0.98, 0.96, 0.95, 0.95, 0.94, 0.91, 0.87, 0.83],
    solar: solar(5.3, 18.7, 0.62),
    wind: wind(0.12, 0.04, 3),
    events: [{ timeMin: 780, type: 'clouds', factor: 0.45, durationMin: 50 }],
  },
  {
    id: 'summerWeekend',
    name: 'Summer weekend',
    description: 'A Sunday in July. Offices and factories are quieter; demand peaks in the evening when people are home.',
    month: 7,
    weekday: 0,
    peakRatio: 0.86,
    load: [0.82, 0.78, 0.75, 0.73, 0.71, 0.7, 0.7, 0.73, 0.78, 0.83, 0.87, 0.89, 0.88, 0.89, 0.91, 0.93, 0.94, 0.95, 0.97, 1.0, 0.99, 0.96, 0.92, 0.86],
    solar: solar(5.3, 18.7, 0.6),
    wind: wind(0.12, 0.04, 3),
    events: [],
  },
  {
    id: 'winterWeekday',
    name: 'Winter weekday',
    description: 'A Wednesday in January. Lower demand, short days with weaker sun, and strong northeast-monsoon winds.',
    month: 1,
    weekday: 3,
    peakRatio: 0.78,
    load: [0.7, 0.66, 0.64, 0.63, 0.63, 0.66, 0.72, 0.82, 0.92, 0.97, 0.99, 0.99, 0.92, 0.96, 0.98, 0.97, 0.96, 0.97, 1.0, 0.99, 0.95, 0.89, 0.82, 0.76],
    solar: solar(6.5, 17.4, 0.48),
    wind: wind(0.55, 0.08, 4),
    events: [],
  },
  {
    id: 'winterWeekend',
    name: 'Winter weekend',
    description: 'A Saturday in January. Low demand with plenty of wind and midday sun: watch for too much generation.',
    month: 1,
    weekday: 6,
    peakRatio: 0.68,
    load: [0.76, 0.72, 0.7, 0.68, 0.67, 0.68, 0.71, 0.76, 0.83, 0.88, 0.91, 0.92, 0.9, 0.9, 0.9, 0.9, 0.91, 0.95, 1.0, 0.99, 0.95, 0.9, 0.85, 0.8],
    solar: solar(6.5, 17.4, 0.48),
    wind: wind(0.58, 0.08, 4),
    events: [],
  },
  {
    id: 'lunarNewYear',
    name: 'Lunar New Year',
    description: 'Factories close for the holiday and demand falls to its lowest of the year, while sun and wind keep producing.',
    month: 2,
    weekday: 1,
    peakRatio: 0.56,
    load: [0.82, 0.78, 0.75, 0.73, 0.72, 0.72, 0.73, 0.76, 0.8, 0.85, 0.89, 0.91, 0.9, 0.9, 0.9, 0.9, 0.91, 0.95, 1.0, 0.99, 0.97, 0.94, 0.9, 0.86],
    solar: solar(6.4, 17.7, 0.5),
    wind: wind(0.5, 0.08, 4),
    events: [],
  },
  {
    id: 'typhoon',
    name: 'Typhoon day',
    description: 'A typhoon day off in August. Offices close, clouds block the sun, and in the afternoon the wind becomes too strong: turbines shut down to protect themselves.',
    month: 8,
    weekday: 4,
    peakRatio: 0.8,
    load: [0.84, 0.8, 0.77, 0.75, 0.74, 0.73, 0.74, 0.77, 0.82, 0.87, 0.9, 0.92, 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.98, 1.0, 0.99, 0.96, 0.92, 0.88],
    solar: solar(5.5, 18.5, 0.15),
    wind: wind(0.45, 0.15, 13),
    events: [{ timeMin: 840, type: 'windCutout', factor: 0.1, durationMin: 480, rampMin: 120, warnMin: 240 }],
  },
];

const out = {
  _comment: 'Generated by tools/make-days.js. load: hourly demand as a fraction of the day\'s peak; peakRatio: the day\'s peak as a fraction of the annual peak; solar/wind: hourly fleet capacity factors.',
  dataStatus: 'placeholder',
  days,
};

// Keep number arrays on one line so the file stays readable.
const json = JSON.stringify(out, null, 2).replace(/\[\s*([-\d.,\s]+?)\s*\]/g, (_, body) => `[${body.split(/\s*,\s*/).join(', ')}]`);
writeFileSync(new URL('../data/days.json', import.meta.url), json + '\n');
console.log(`Wrote ${days.length} day types to data/days.json`);
